name: SonarCloud Scan and Tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Test and SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose  # Ensure docker-compose is available
  
      - name: Set up Docker Compose
        run: docker-compose -f docker-compose-kafka-tests.yml up -d
        

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Kafka Connection
        run: |
          echo "Testing Kafka connection..."
          nc -zv localhost 9092 || echo "Connection to Kafka failed"

      - name: Run Tests
        env:
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
          ENV: development
          SMTP_HOST: "smtp.test.com"
          SMTP_PORT: "587"
          SMTP_USER: "test_user@test.com"
          SMTP_PASS: "test_password"
        run: |
          pytest --cov=./ --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.projectBaseDir=./ -Dsonar.python.coverage.reportPaths=coverage.xml